---
- name: Gather ACI facts (Cisco)
  block:
    - setup:
        gather_subset:
          - 'all'
      delegate_to: "{{ ansible_host }}"

    - set_fact:
        brand: cisco
        ansible_network_os: aci
        ansible_net_hostname: "{{ ansible_hostname }}"
        ansible_net_version: " "
  rescue:
    - debug:
        msg: "This is not a Cisco ACI device :("
  when:
    ansible_net_hostname is not defined or brand is not defined
