---
- hosts: cisco
  gather_facts: no
  connection: local

  tasks:
  - nxos_facts:
      gather_subset: all

  - name: Get backup
    nxos_config:
      backup: yes
      backup_options:
        filename: "{{ ansible_net_hostname }}.cfg"
        dir_path: "{{ playbook_dir }}/cfg/"

  - name: Remove lines
    lineinfile:
      path: "{{ playbook_dir }}/cfg/{{ ansible_net_hostname }}.cfg"
      state: absent
      regexp: "{{ item }}"
    with_items:
      - '^!Time'
      - '^!Command'
      - '^!Running configuration '
