---
- name: Getting IOS Facts
  ios_facts:

- name: Mapping OS Compliance Version
  set_fact:
    hardening_file: "{{ compliance_file_mapping[ansible_net_version] }}"


- name: Importing vars file
  include_vars:
    file: "vars/{{ hardening_file }}.yml"
  ignore_errors: yes

- name: Issue Show Run Command
  ios_command:
    commands:
       - show run all
    timeout: 60
  register: run

- name: Create Output Folder
  file:
    path: "{{ path }}"
    state: directory
    mode: '0755'

- name: create HTML report
  template:
    src: "report-ios.j2"
    dest: "{{ path }}/{{ filename }}"
  delegate_to: localhost
  run_once: true
