---
# tasks file for ciscoComplianceCheck
#- set_fact:
#    ansible_host: "{{ inventory_hostname }}"

- name: Getting IOS Facts
  ios_facts:

- name: Mapping OS Compliance Version
  set_fact:
    hardening_file: "{{ item.value }}"
  loop: "{{ lookup('dict', compliance_file_mapping) }}"
  when: "'{{ ansible_net_version }}' in item.key"

- name: Importing vars file
  include_vars:
    file: "vars/{{ hardening_file }}.yml"
  ignore_errors: yes

- name: Issue Show Run Command
  ios_command:
    commands:
       - show run all
       - show run | i snmp
    timeout: 60
  register: run

- set_fact:
    showRun: "{{ (run.stdout_lines[0] + \
                  run.stdout_lines[1]) | join('\n') }}"

- name: create HTML report
  template:
    src: "./files/report-ios.j2"
    dest: "{{ playbook_dir }}/generated_report.html"
  delegate_to: localhost
  run_once: true
