---
# tasks file for generate_report
- name: ISSUE SHOW INVENTORY COMMAND
  ios_command:
    commands:
      - "show inventory\n"
  register: inv_raw

- set_fact:
    inv: "{{ inv_raw.stdout_lines[0]  }}"

- name: GATHER UPDATED FACTS
  nxos_facts:
    gather_subset: all 

- name: create HTML report
  template:
    src: "./files/report-ios.j2"
    dest: "./generated_report.html"
  delegate_to: localhost
  run_once: true
