---
- name: Adding Host to memory
  hosts: localhost
  gather_facts: no
  tasks:
  - add_host:
      name: "{{ http_server }}"
      group: new_centos_vm


- name: Configuring HTTP server
  hosts: new_centos_vm
  become: true

  roles:
    - provision_webserver
